### ISSUE TITLE
when can we expect the open-sourcing of the AnyText code?

### ISSUE THREAD

**Issue by ninjasaid2k** [tyxsspa/AnyText#1]

**Comment by tyxsspa** [comment]
Hi, expected in early December, please stay tuned.

**Comment by SiyuanHuang95** [comment]
And how about the text-ocr dataset? Will they be open-sourced with the code? Or can we get the dataset earlier?

**Comment by ZhendongWang6** [comment]
Cool work! Looking forward the release of the code. Thank you!

**Comment by SanyamLakhanpal** [comment]
Hi team, thank you for your awesome work !! But still looking for your open source implementation.

**Comment by SKDDJ** [comment]
waiting for datasets and training code. :eyes:
