### ISSUE TITLE
Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by ECHO2008** [tyxsspa/AnyText#100]
当设置 "use_translator": True 时，执行图像成成报错，Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)

**Comment by tyxsspa** [comment]
加上 `export CUDA_VISIBLE_DEVICES=0`

**Comment by ECHO2008** [comment]
已解决
