### ISSUE TITLE
OCR model may not load pretrained weights?

### ISSUE THREAD

**Issue by JuntaoLiu01** [tyxsspa/AnyText#110]
Thanks for the excellent work. When reading the training codes, I found that the ocr model does not load pretrained weights. Is it a bug or did I do something wrong? 

Hope for your reply!

The code is: 
```
if self.loss_alpha > 0 or self.loss_beta > 0 or self.embedding_manager:
    if embedding_manager_config.params.emb_type == 'ocr':
        self.text_predictor = create_predictor().eval()
        args = edict()
        args.rec_image_shape = "3, 48, 320"
        args.rec_batch_num = 6
        args.rec_char_dict_path = './ocr_recog/ppocr_keys_v1.txt'
        args.use_fp16 = self.use_fp16
        self.cn_recognizer = TextRecognizer(args, self.text_predictor)
        for param in self.text_predictor.parameters():
            param.requires_grad = False
        if self.embedding_manager:
            self.embedding_manager.recog = self.cn_recognizer
```

the `self.text_predictor = create_predictor().eval()` may need a weight path.

**Comment by tyxsspa** [comment]
The ocr model's weights are already copied when generating `anytext_sd15_scratch.ckpt` using `tool_add_anytext.py`.

**Comment by JuntaoLiu01** [comment]
> The ocr model's weights are already copied when generating `anytext_sd15_scratch.ckpt` using `tool_add_anytext.py`.

Thanks. I missed the step.
