### ISSUE TITLE
May I ask how to maintain modifications to the model code file?

### ISSUE THREAD

**Issue by wendashi** [tyxsspa/AnyText#111]
When I try to change the code in '/path/to/.cache/modelscope/modelscope_modules/cv_anytext_text_generation_editing/ms_wrapper.py', I found it would be downloaded from modelscope every time, so the modifications are covered.

and i try to change the source code
`pipe = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.3')
`

to use  local path

` pipe = pipeline('my-anytext-task', model='/path/to/.cache/modelscope/modelscope_modules/cv_anytext_text_generation_editing', model_revision='v1.1.3')
`

It turns out as following:  

```
type must be a str or valid type, but got <class 'NoneType'>
  File "/path/to/AnyText/inference.py", line 14, in <module>
    pipe = pipeline('my-anytext-task', model=model_path, model_revision='v1.1.3')
TypeError: type must be a str or valid type, but got <class 'NoneType'>
```

Hope you can provide me some advice, THX a lot ❤️

**Comment by tyxsspa** [comment]
try modify this file instead: 
/path/to/.cache/modelscope/hub/damo/cv_anytext_text_generation_editing/ms_wrapper.py

**Comment by tyxsspa** [comment]
No,

**Comment by tyxsspa** [comment]
No, not `/home/stone/.cache/modelscope/modelscope_modules/cv_anytext_text_generation_editing/ms_wrapper.py`, but `/home/stone/.cache/modelscope/hub/damo/cv_anytext_text_generation_editing/ms_wrapper.py`😄

**Comment by wendashi** [comment]
The same error 😂

![image](https://github.com/tyxsspa/AnyText/assets/141135497/0ffe8600-cb54-4f1b-86b6-9477c44d92b0)

**Comment by tyxsspa** [comment]
keep the default value of  `model='damo/cv_anytext_text_generation_editing'`, then modelscope will find the ms_wrapper.py there.

**Comment by wendashi** [comment]
I see, Thank U so much!

I only need to modify this file instead:
/path/to/.cache/modelscope/hub/damo/cv_anytext_text_generation_editing/ms_wrapper.py

and keep `pipe = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.3') ` as default.
