### ISSUE TITLE
Does it support curved texts?

### ISSUE THREAD

**Issue by bowen-upenn** [tyxsspa/AnyText#120]
In the methodology pipeline, the region of "BEVELRLY" is curved, following the curvature of texts in the image. However, we tested many examples in the dataset and found that all annotated polygons only have four points, even if the texts are curved. 

For example, below is the `position` of the texts "POWER" in the image with a polygon with a length of 4:
```
[[273 508]
 [229 446]
 [445 294]
 [489 357]]
```
 Is this expected? How should we handle the curved texts? We didn't modify the dataset annotations, polygons, or the positions. Thanks!!

<img width="507" alt="Screenshot 2024-08-06 at 4 15 59 PM" src="https://github.com/user-attachments/assets/bfcdfc1e-ed33-43ea-9b0f-e46513517175">

![000149739_pos](https://github.com/user-attachments/assets/d9477fe4-c1cb-49d6-b113-3d7f0c60662d)

**Comment by tyxsspa** [comment]
Well, most of the polygons were annotated by PPOCR-v4 and have only four points, only images from OCR datasets have curved polygons from human-annotated labels. Even trained using rectangle polygons, anytext can generate text in curved regions(refer [replay](https://openreview.net/forum?id=ezBH9WE9s2&noteId=NfOrlwuogi) in openreview)
