### ISSUE TITLE
Huggingface space doesn't work

### ISSUE THREAD

**Issue by tolgacangoz** [tyxsspa/AnyText#122]
Great work @tyxsspa!

[The demo at Hugging Face space doesn't work.](https://huggingface.co/spaces/modelscope/AnyText)

**Comment by tyxsspa** [comment]
available now, just restarted @tolgacangoz

**Comment by tolgacangoz** [comment]
Thanks!

**Comment by ElementTech** [comment]
Hey, it doesn't work again @tyxsspa

**Comment by tyxsspa** [comment]
@ElementTech  Hi~ just restarted!
