### ISSUE TITLE
The missing `LayerNorm(token_dim)` parameters in the checkpoint file?

### ISSUE THREAD

**Issue by tolgacangoz** [tyxsspa/AnyText#123]
Hi @tyxsspa!

I might be wrong: In the code, there is a `LayerNorm(token_dim)` in the `embedding_manager` for `self.proj`:
https://github.com/tyxsspa/AnyText/blob/c1ffbb42b007ac7c93c584913554c95714ab285e/cldm/embedding_manager.py#L104-L108

In the checkpoint file of `anytext_v1.1.ckpt`, there are "embedding_manager.proj.weight", and "embedding_manager.proj.bias" for the linear layer but no parameters for the `LayerNorm(token_dim)`. Is this correct?

**Comment by tyxsspa** [comment]
Yes, it's correct. The `LayerNorm` was added recently to fix reproduce stablility(see #98 )

**Comment by tolgacangoz** [comment]
Ah, I missed that; OK :+1:. So, the inference code doesn't have `LayerNorm`.
