### ISSUE TITLE
加载模型权重文件anytext_v1.1.ckpt报错

### ISSUE THREAD

**Issue by Hxiangdou** [tyxsspa/AnyText#131]
加载模型权重文件报错model.load_state_dict(load_state_dict(args.ckpt_path, location='cuda'))    
        raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlLDM:
        Missing key(s) in state_dict: "embedding_manager.proj.0.weight", "embedding_manager.proj.0.bias", "embedding_manager.proj.1.weight", "embedding_manager.proj.1.bias". 
        Unexpected key(s) in state_dict: "cond_stage_model.transformer.text_model.embeddings.position_ids", "embedding_manager.proj.weight", "embedding_manager.proj.bias".

**Comment by chenxinhua** [comment]
同样遇到

**Comment by tyxsspa** [comment]
对齐一下transformer 版本
https://github.com/open-mmlab/PIA/issues/13#issuecomment-1868421893

**Comment by Hxiangdou** [comment]
修改了./cldm/embedding_manager.py的105行，
将
`            self.proj = nn.Sequential(
                            zero_module(linear(40*64, token_dim)),
                            nn.LayerNorm(token_dim)
                            )
`
改为
`            self.proj = zero_module(linear(40*64, token_dim))`

修改后可以正常运行，同时要保证transformer版本与environment.yaml相同。
