### ISSUE TITLE
No preprocessor key ('my-custom-model', 'my-anytext-task') found in PREPROCESSOR_MAP, skip building preprocessor

### ISSUE THREAD

**Issue by yuetz** [tyxsspa/AnyText#16]
工作很棒。
但是使用给的代码完全不能复现效果。怀疑是这个warning的提示的原因：No preprocessor key ('my-custom-model', 'my-anytext-task') found in PREPROCESSOR_MAP, skip building preprocessor
也就是说my-anytext-task 这个task的预处理流程没有定义。是因为modelscope的版本问题吗？或者其他原因？
谢谢！

**Comment by tyxsspa** [comment]
你好，能否贴图看下效果？是否按照文档安装的环境？确实某些库的版本号和yaml不一致会有些差异，比如opencv的某些版本会导致某些预处理函数输出不一致，从而改变出图效果。

**Comment by yuetz** [comment]
<img width="740" alt="image" src="https://github.com/tyxsspa/AnyText/assets/5548228/28210d7e-1dc3-4359-8e73-7335cc5fcb7e">

**Comment by yuetz** [comment]
<img width="737" alt="image" src="https://github.com/tyxsspa/AnyText/assets/5548228/ca78f1a4-5fdc-48e4-be92-f019ae44f620">

**Comment by yuetz** [comment]
感谢你的及时回复。上面是文本编辑的两个例子。使用的例子和example中的完全之一。生成的字和输入的文本没有什么关系。不知道是哪里配置的问题

**Comment by tyxsspa** [comment]
看起来是prompt中没有提供要写入的文字？需要用双引号包起来，比如第二张图是：`精美的书法作品，上面写着“志” “存” “高” ”远“`

**Comment by yuetz** [comment]
> 你好，能否贴图看下效果？是否按照文档安装的环境？确实某些库的版本号和yaml不一致会有些差异，比如opencv的某些版本会导致某些预处理函数输出不一致，从而改变出图效果。

是按照文档环境安装的。唯一不同的是.cache/modelscope中下载的内容。我把.cache/modelscope/hub/中的文件copy到了内网。.cache/modelscope/ast_indexer文件是自动生成的。

> 看起来是prompt中没有提供要写入的文字？需要用双引号包起来，比如第二张图是：`精美的书法作品，上面写着“志” “存” “高” ”远“`

是的，都生成了默认的“口”，或者“日”。字体文件是有的。ast_index文件是自动生成的。和这个有关系吗？

**Comment by yuetz** [comment]
> 看起来是glyph图像的文字没有正确渲染，请问你使用的是什么ttf文件？可以在parameters中打开Show Debug选项，结果中会显示glyph图，观察字体是否被正确render。如果都是错误的(比如方块),那可能选择的ttf文件有问题。推荐arial unicode，这个搜索引擎找一下就可以下载到。

字体引擎使用的是arial unicode。稍后我重新下载一下。
打开debug之后，显示：
Prompt: Exquisite calligraphy, it says "志" "存" "高" "远"
Size: 512x512
Image Count: 4
Seed: 98053044
Cost Time: 12.19s
但是没有show glyph图像。可能同样的错误原因吗？

**Comment by yuetz** [comment]
多谢！是字体文件的原因。之前下载的是一个阉割版的字体文件。
再次感谢

**Comment by 2499048212** [comment]
您好，我也遇到的相似的问题，更改了许多个字体都没成功，可以请您分享一下您使用的字体嘛？万分感谢
