### ISSUE TITLE
由于网络原因,下载anytext_v1.1.ckpt失败

### ISSUE THREAD

**Issue by Wangxunhang** [tyxsspa/AnyText#29]
由于隔离网络环境连不上modelscope,我自行下载了官方提供的模型文件夹/cv_anytext_text_generation_editing/, 并放在了~/.cache/modelscope/hub/damo/目录下,但是在运行demo.py时依然会自动执行下载导致报错,请问如何绕过自动下载?

**Comment by tyxsspa** [comment]
自行下载的话，可以随意放到某个目录，然后修改这行代码：
https://github.com/tyxsspa/AnyText/blob/main/demo.py#L21
```
inference = pipeline('my-anytext-task', model='your/path/to/cv_anytext_text_generation_editing', model_revision='v1.1.0')
```

**Comment by Wangxunhang** [comment]
感谢!
