### ISSUE TITLE
运行成功的朋友，你们用的cuda、cudnn、tensorflow的版本是多少

### ISSUE THREAD

**Issue by zlht812** [tyxsspa/AnyText#40]
按照官方的方案已经安装没有报错，可以运行demo的页面，但点击推理时会报以下错误：
Global seed set to 81808278
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.808 seconds.
Prefix dict has been built successfully.
WARNING:tensorflow:From /root/anaconda3/envs/anytext/lib/python3.10/site-packages/modelscope/utils/device.py:60: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2024-01-06 13:43:02.314823: F ./tensorflow/core/util/gpu_launch_config.h:169] Check failed: err == cudaSuccess (302 vs. 0)
Aborted
怀疑是tf和cuda的版本不对。

我的版本如下：
3080ti
cuda 11.8
cudnn 8.5
tensorflow 2.13

**Comment by catsled** [comment]
这应该是pytorch版的吧
