### ISSUE TITLE
How to calculate z0' for rebuliting the image x0' when training?

### ISSUE THREAD

**Issue by yuetz** [tyxsspa/AnyText#54]
Thanks for your attention. 

When training the cldm, I get the noise using`model_output = self.apply_model(x_noisy, t, cond)` given the `parameterization='eps'`. I want to rebuilt the image. What param need be passed to the func `self.decode_first_stage(???)`.

I think `self.decode_first_stage(x_noisy - model_output)` is wrong. But I do not now the right way.

`x_noisy = self.q_sample(x_start=x_start, t=t, noise=noise)`
`model_output = self.apply_model(x_noisy, t, cond)`
`# self.parameterization == "eps"`
`imgs = self.decode_first_stage(x_noisy - model_output)`

**Comment by tyxsspa** [comment]
Hi~ 
You should pass a latent without noise(z_0) into self.decode_first_stage, which will transfrom z_0 to x_0 (image). But x_noisy is noisy latent with t steps(z_t) and model_output is the predicted noise, pass the difference of them into VAE decoder make no sense. There's a way to predict the ”approximate“ z_0 from x_noisy, model_output and timestep t, you can check this function: DDPM::predict_start_from_noise().

**Comment by yuetz** [comment]
Thanks for your answer.
