### ISSUE TITLE
About Chinese text

### ISSUE THREAD

**Issue by tengjiayan20** [tyxsspa/AnyText#58]
Excellent work! But when I run demo locally, why can't I render Chinese words correctly? It seems that I don't have proper Chinese fonts file. Could you please tell us what the exact Chinese fonts file is required?

**Comment by tyxsspa** [comment]
Arial Unicode MS is recommended. Try download here https://github.com/tyxsspa/AnyText/issues/19#issuecomment-1873704703

**Comment by tengjiayan20** [comment]
Thank you! The version I download before is wrong.
