### ISSUE TITLE
CFG Resolution Weighting of ControlNet

### ISSUE THREAD

**Issue by tengjiayan20** [tyxsspa/AnyText#60]
Excellent work!
Could I ask more details? Do you use CFG Resolution Weighting of ControlNet in this work? And if so, could you tell where the code  is?
Thank you very much!!!

**Comment by tyxsspa** [comment]
We did not use CFG Resolution Weighting, and it seems like ControlNet was also not used (I didn't see any relevant code, please point it out if I'm mistaken)

**Comment by tengjiayan20** [comment]
Thank you for your patient explanation!
I also didn't see any relevant codes in ControlNet repo.
