### ISSUE TITLE
what's the purpose of setting the hyperparameter mask_img_prob?

### ISSUE THREAD

**Issue by Zhaohuii-Wang** [tyxsspa/AnyText#79]
Thanks for the great work！
I noticed that the t3dataset contains the hyperparameter mask_img_prob while attempting to replicate the training. From the code, it appears that three masks different from the orc mask will be randomly added to the image based on this probability value. What is the purpose of this and will it have a positive impact on the training？

**Comment by tyxsspa** [comment]
Hi, in text editing mode, the model needs to inpaint not only the text area but also the background area. The parameter mask_img_prob is used to randomly generate masks on non-text areas. In my opinion (though not tested), this might slightly impair text generation but enhance text editing capabilities.

**Comment by Zhaohuii-Wang** [comment]
Thanks for the relpy. I have similar idea! I will close this issue.
