### ISSUE TITLE
从一个新的checkpoint继续训练，代码没有任何输出就结束运行了

### ISSUE THREAD

**Issue by 588ustczf** [tyxsspa/AnyText#90]
您好，感谢您提供的开源代码以及数据集，对我有很大的帮助。但是我遇到了一个问题，如果我一开始使用anytext_sd15_scratch.ckpt训练2个epoch是没有任何问题的，然后保存这个阶段的checkpoint，之后再重新从这个checkpoint开始后面几轮的训练，代码总是加载完数据集后就自动结束，也没有任何报错，是什么原因呢。而且我这里两轮过后的checkpoint保存下来的大小有8G多，为啥比anytext_sd15_scratch.ckpt和anytext_v1.1.ckpt都大那么多，这两个都只有5G多。如果您知道原因，麻烦解答一下。非常感谢~

**Comment by tyxsspa** [comment]
1. 加载完数据集就结束？检查下train.py是不是设置了max_epochs=2了？
2. ckpt 8G是正常的，release的5G模型只保留了必要的state_dict参数。
