### ISSUE TITLE
部署效果差

### ISSUE THREAD

**Issue by mcx-mcx** [tyxsspa/AnyText#99]
请问本地部署时，跑测试样例都效果不好可能是什么原因造成的
![Snipaste_2024-06-03_16-46-24](https://github.com/tyxsspa/AnyText/assets/71203199/4692109c-f5bf-40ae-8e85-6d674ad3a47a)

**Comment by myungkyuKoo** [comment]
@mcx-mcx I'm also experiencing this problem. Have you solved it?
